-- Apply once to existing D1 databases BEFORE deploying the worker build that
-- carries the effective-scope credential model.
--
-- Ordering matters and only in this direction: adding the column is invisible
-- to the currently deployed code (it selects columns by name), while deploying
-- the new code against an un-migrated database would fail every credential read
-- — i.e. every authenticated request. Migrate first, deploy second.
--
-- What the column means: a credential is a ceiling only when narrowed = 1.
-- Every row that exists today gets 0, which is correct and is NOT a backfill
-- awaiting a better answer. Those rows are snapshots of role policy taken on
-- their pairing day, never deliberate restrictions — createDeviceCredential
-- accepted no scopes parameter until now, so no credential in the fleet has
-- ever been narrowed on purpose. At 0 they track live role policy in both
-- directions, which is the whole point of the change: editing DEVICE_SCOPES
-- now grants AND withdraws on the next request, with no re-pair.
--
-- Not idempotent: SQLite has no ADD COLUMN IF NOT EXISTS, so a second run
-- fails loudly with "duplicate column name: narrowed". That is the intended
-- behaviour for a re-run — nothing is changed and nothing is silently skipped.
ALTER TABLE relay_device_credentials
  ADD COLUMN narrowed INTEGER NOT NULL DEFAULT 0;
