[platformio]
default_envs = featheresp32

[env:featheresp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = featheresp32
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
lib_deps =
  https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.11
  bblanchon/ArduinoJson@^7.4.2
build_flags =
  -DCORE_DEBUG_LEVEL=3
