"""Build packed lexicon blobs for knob_decode.c and test cases generated by sim.py."""
import math, struct, sys
import numpy as np
import sim

COST_Q = 0.1
MAXU = 15

def symbols(word):
    return [sim.IDX[c] * 2 + d for c, d in sim.collapse(word)]

def build_blob(words, prior):
    ent = []
    for w, p in zip(words, prior):
        s = symbols(w)
        if len(s) > MAXU: continue
        ent.append((s, w, min(255, int(round(-math.log(p) / COST_Q)))))
    ent.sort()
    out = bytearray(struct.pack("<IB", len(ent), MAXU))
    prev = []
    for s, w, cost in ent:
        lcp = 0
        while lcp < min(len(s), len(prev), 15) and s[lcp] == prev[lcp]: lcp += 1
        suf = s[lcp:]
        out += bytes([(lcp << 4) | len(suf), cost])
        bits = nb = 0
        for x in suf:
            bits = bits << 6 | x; nb += 6
            while nb >= 8: out.append((bits >> (nb - 8)) & 255); nb -= 8
        if nb: out.append((bits << (8 - nb)) & 255)
        prev = s
    return bytes(out), len(ent)

def main(kind, sigma=0.75, n_cases=300, layout="uniform"):
    words, prior = sim.make_lexicon(kind)
    blob, n = build_blob(words, prior)
    open(f"lex_{kind}.bin", "wb").write(blob)
    centers, fac = sim.layout(layout)
    rng = np.random.default_rng(11)
    user = sim.User(sigma, rng)
    lex = sim.Lex(words, prior, centers)
    dec = sim.Decoder(lex, centers, fac, sigma, b=user.b, s=user.s)
    mu = 13 + user.s * (centers - 13) + user.b
    sd = np.maximum(sigma * fac, 0.15)
    lf = dec.lf
    with open(f"cases_{kind}.txt", "w") as f:
        f.write(" ".join(f"{x:.5f}" for x in mu) + "\n" + " ".join(f"{x:.5f}" for x in sd) + "\n")
        f.write(f"{dec.lpd:.6f} {dec.lpi:.6f} {dec.lmatch:.6f} {lf[(1,1)]:.6f} {lf[(0,1)]:.6f} {lf[(1,0)]:.6f} {lf[(0,0)]:.6f} 1.0 {dec.gap}\n")
        py_ok = 0
        for w in rng.choice(len(words), n_cases, p=prior):
            o, fl, _ = sim.observe(words[w], user, centers, fac, rng)
            top = words[int(np.argmax(dec.scores(o, fl)))]
            py_ok += top == words[w]
            f.write(f"{words[w]} {top} {len(o)} " + " ".join(f"{x:.4f} {int(g)}" for x, g in zip(o, fl)) + "\n")
    # size of a plain (uncompressed) representation for comparison
    plain = sum(len(w) + 1 + 1 for w in words)
    print(f"{kind}: {n} words, packed blob {len(blob)} B ({len(blob)/n:.2f} B/word), plain strings+cost {plain} B; python top1 {py_ok/n_cases:.3f}")

if __name__ == "__main__":
    for k in sys.argv[1:] or ["commands", "5k", "20k"]:
        main(k)
