#!/usr/bin/env python3
"""Generate src/tx_resample_taps.h — the 24000 -> 31250 polyphase table.

Run: python3 scripts/gen_tx_taps.py > src/tx_resample_taps.h

The table is emitted as const data for flash rather than built at boot:
the nRF9160 app is compiled soft-float (CONFIG_FPU is not set), so a runtime
builder would pull in softfloat sinf/cosf and spend RAM the audio path does
not have.
"""
import math
import sys

TAPS = 12
PHASES = 125            # == TX_RESAMPLE_DEN; gcd(96,125)==1 so every residue
                        # is visited and the table is EXACT — nothing to blend
CUTOFF = 10500.0        # not 12 kHz: at 125/96 an 11.9 kHz component images to
                        # 12.1 kHz and no filter can separate the two
FS_IN = 24000.0
Q = 14                  # max sum|h| 27044; 27044*32768 < INT32_MAX


def build():
    n = PHASES * TAPS
    center = (n - 1) / 2.0
    band = 2.0 * CUTOFF / FS_IN
    table = []
    for phase in range(PHASES):
        row, total = [], 0.0
        for tap in range(TAPS):
            index = phase + tap * PHASES
            x = (index - center) * band / PHASES
            arg = math.pi * x
            sinc = 1.0 if abs(x) < 1e-9 else math.sin(arg) / arg
            # Hamming, matching the ESP32's 625/882 stage so the two
            # resamplers do not stack two different passband ripples.
            window = 0.54 - 0.46 * math.cos(2.0 * math.pi * index / (n - 1))
            row.append(sinc * window)
            total += row[-1]
        if total == 0.0:
            total = 1.0
        # Unity DC gain PER PHASE, else level ripples at the phase-cycle rate.
        table.append([max(-32768, min(32767, int(round(v / total * (1 << Q)))))
                      for v in row])
    return table


def main():
    table = build()
    w = sys.stdout.write
    w("/*\n * GENERATED by scripts/gen_tx_taps.py -- do not edit by hand.\n")
    w(" * 24000 -> 31250 polyphase interpolator: %d phases x %d taps, Q%d,\n"
      % (PHASES, TAPS, Q))
    w(" * Hamming-windowed sinc, cutoff %.0f Hz.\n */\n" % CUTOFF)
    w("#ifndef TX_RESAMPLE_TAPS_H_\n#define TX_RESAMPLE_TAPS_H_\n\n")
    w("#include <stdint.h>\n\n")
    w("#define TX_FIR_TAPS %du\n#define TX_FIR_PHASES %du\n#define TX_FIR_Q %d\n\n"
      % (TAPS, PHASES, Q))
    w("static const int16_t tx_fir_coeff[TX_FIR_PHASES * TX_FIR_TAPS] = {\n")
    for phase, row in enumerate(table):
        w("\t/* phase %3d */ " % phase)
        w(", ".join("%6d" % v for v in row))
        w(",\n")
    w("};\n\n#endif /* TX_RESAMPLE_TAPS_H_ */\n")


if __name__ == "__main__":
    main()
